# Generated by Django 2.2.1 on 2019-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteApp', '0003_auto_20190520_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAndFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
