# Generated by Django 2.2.1 on 2019-05-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteApp', '0004_imageandfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageandfile',
            name='image',
        ),
    ]
