# Generated by Django 2.2.1 on 2019-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteApp', '0005_remove_imageandfile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAndFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='myDjangoProject/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageAndFile',
        ),
    ]
