# Generated by Django 3.0.6 on 2020-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteApp', '0006_auto_20190525_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageandfilemodel',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='item',
            field=models.CharField(choices=[('momo', 'momo'), ('pizza', 'pizza'), ('chwela baji', 'chwela baji'), ('newari khaja set', 'newari khaja set'), ('chicken chilly', 'chicken chilly'), ('coffee', 'coffee')], max_length=50),
        ),
    ]
